# Generated by Django 5.1.4 on 2025-01-12 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='shoppingcartproduct',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
