openapi: 3.0.3
info:
  title: Fridge Inventory Management API
  description: API для управления содержимым холодильника и отслеживания продуктов.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /products:
    get:
      summary: Получить список всех продуктов в холодильнике
      responses:
        '200':
          description: Список продуктов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Добавить новый продукт в холодильник
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Продукт добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /products/{id}:
    get:
      summary: Получить информацию о продукте по его ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: ID продукта
      responses:
        '200':
          description: Информация о продукте
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Продукт не найден
    delete:
      summary: Удалить продукт из холодильника по ID
      parameters:
        - in: path
          name: id
          schema:
            type: string
            format: uuid
          required: true
          description: ID продукта
      responses:
        '204':
          description: Продукт удален
        '404':
          description: Продукт не найден
  /products/search:
    get:
      summary: Найти продукты по названию или категории
      parameters:
        - in: query
          name: name
          schema:
            type: string
          required: false
          description: Название продукта
        - in: query
          name: category
          schema:
            type: string
          required: false
          description: Категория продукта
      responses:
        '200':
          description: Результаты поиска продуктов с учетом названия или категории
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/log:
    get:
      summary: Получить лог действий над продуктами
      description: Возвращает список действий (добавление, удаление и т. д.) с деталями по каждому продукту
      responses:
        '200':
          description: Лог действий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductLog'
  /analytics:
    get:
      summary: Получить аналитику потребления продуктов
      description: Возвращает статистику потребления продуктов за указанный временной период
      parameters:
        - in: query
          name: start_date
          schema:
            type: string
            format: date-time
          required: true
          description: Начальная дата периода анализа
        - in: query
          name: end_date
          schema:
            type: string
            format: date-time
          required: true
          description: Конечная дата периода анализа
      responses:
        '200':
          description: Аналитика потребления продуктов
          content:
            application/json:
              schema:
                type: object
                properties:
                  total_added:
                    type: integer
                    description: Общее количество добавленных продуктов за период
                  total_removed:
                    type: integer
                    description: Общее количество удаленных продуктов за период
                  category_stats:
                    type: object
                    additionalProperties:
                      type: integer
                      description: Количество продуктов по категориям за период
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор продукта
        name:
          type: string
          description: Название продукта
        category:
          type: string
          description: Категория продукта
        manufacturer:
          type: string
          description: Производитель продукта
        quantity:
          type: number
          format: float
          description: Количество продукта
        unit:
          type: string
          description: Единица измерения
        nutritional_value:
          type: number
          format: float
          description: Пищевая ценность продукта
        total_net_weight:
          type: number
          format: float
          description: Чистый вес продукта
        total_gross_weight:
          type: number
          format: float
          description: Вес продукта с упаковкой
        manufacture_date:
          type: string
          format: date-time
          description: Дата изготовления
        expiration_date:
          type: string
          format: date-time
          description: Дата истечения срока годности
        notes:
          type: string
          description: Дополнительные заметки
        allergens:
          type: string
          description: Информация об аллергенах
    ProductLog:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор записи
        product_id:
          type: string
          format: uuid
          description: ID связанного продукта
        action_type:
          type: string
          description: Тип действия (добавление, удаление и т. д.)
        description:
          type: string
          description: Описание действия
        timestamp:
          type: string
          format: date-time
          description: Время действия
