# Generated by Django 5.1.4 on 2025-01-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlog',
            name='quantity_change',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
