# Generated by Django 5.1.4 on 2025-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_log', '0002_productlog_quantity_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlog',
            name='product',
        ),
        migrations.AddField(
            model_name='productlog',
            name='product_id',
            field=models.UUIDField(null=True),
        ),
    ]
