# Generated by Django 5.1.4 on 2024-12-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allergens',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productlog',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
