# Generated by Django 5.1.5 on 2025-01-16 16:11

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
