name: Build Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Remove comments and move .env.docker.template to .env.docker
      run: |
        sed 's/#.*//' backend/.env.docker.template > backend/.env.docker

    - name: Build and Push Backend Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/backend:${{ github.sha }} ./backend
        docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}
