name: Build Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Remove comments and move .env.docker.template to .env.docker
      run: |
        sed 's/#.*//' frontend/.env.docker.template > frontend/.env.docker
    
    - name: Set REPO_NAME to lowercase
      run: |
        echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build image
      run: |
        docker build -t ghcr.io/${{ env.REPO_NAME }}/frontend:${{ github.sha }} ./frontend

    - name: Push image
      run: |
        docker push ghcr.io/${{ env.REPO_NAME }}/frontend:latest
        docker push ghcr.io/${{ env.REPO_NAME }}/frontend:${{ github.sha }}
